### ISSUE TITLE
Make a Good CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#10]
Currently the Code of Conduct file references a link with a standard code of conduct. Please do some research and see what others are doing for their code of conduct file. Give a read over the CONTRIBUTION.md file to see some notes about do and don't do's. 

Add when contributing to this repo, use only your own original resources, cc0 or public domain resources. Don't break any copyright laws.

Craft a meaningful reusable code of conduct file for this project. Keep it simple as possible. 

Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by ojasaklechayt** [comment]
@omicreativedev can I work on this ?

**Comment by omicreativedev** [comment]
Yes @ojasaklechayt you are assigned now :)
