### ISSUE TITLE
Create a CONTRIBUTING_pages.md File and Tutorial

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#14]
Within CONTRIBUTING.md you will find:
**PR 1 - Create A New Profile Page in Pages**
Create a link to a **new page** entitled CONTRIBUTING_pages.md and remove the body of this section from CONTRIBUTING.md
In this new CONTRIBUTING_pages.md page, make a **complete** tutorial about how to create a page step by step including git instructions for CLI and Web. We want to make it SUPER EASY for anyone to make a page even if they have no experience. Someone who knows nothing about coding should be able to follow our instructions exactly and make their first successful contribution to this repository. 

Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by SilverDragonOfR** [comment]
Can you assign this to me?
