### ISSUE TITLE
Make a New CONTRIBUTING_themes.md file

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#15]
Within CONTRIBUTING.md you will find:
PR 2 - Create A New THEME
Create a link to a new page entitled CONTRIBUTING_themes.md and remove the body of this section from CONTRIBUTING.md
In this new CONTRIBUTING_themes.md page, make a complete tutorial about how to create a theme step by step including git instructions for CLI and Web. We want to make it SUPER EASY for anyone to make a theme even if they have no experience. Someone who knows nothing about coding should be able to follow our instructions exactly and make their first successful contribution to this repository.

Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Charan2437** [comment]
hey @omicreativedev i would like to contribute

**Comment by omicreativedev** [comment]
@Charan2437 Yes, wonderful. You are assigned. Have fun :)
