### ISSUE TITLE
Create a Feature Suggestion Template for this repo

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#16]
Currently there is no template for feature suggestions.

This is a good starting point:
https://github.com/jfmartinz/ResourceHub/blob/main/.github/ISSUE_TEMPLATE/feature.yml

Most of all, be creative <3
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by ATREAY** [comment]
hey @omicreativedev, can I work on this issue?
