### ISSUE TITLE
Create a MUSIC Theme AND Page

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#19]
![OIP](https://github.com/omicreativedev/hacktoberfest2023/assets/82254764/432501a4-dcac-4b55-9742-5fa6e821b75f)

Make a theme that promotes a new song. **You can use any song you like from spotify, soundcloud, youtube, or something else.** Theme for inspiration but you can be creative as you like. Embed the media in the page and make a theme to match. 

Be creative as you like.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by priyanshu-gupta0503** [comment]
hey@omicreativedev I would love to create the theme that pramotes a new song. 
kindly assign this issue to me.

**Comment by omicreativedev** [comment]
@priyanshu-gupta0503 Yes, absolutely. Have fun!

**Comment by priyanshu-gupta0503** [comment]
thank you so much@omicreative

**Comment by priyanshu-gupta0503** [comment]
hey@omicreative i want to ask a query that in the code  on changing the theme drop down the theme is not changing .
could you please brief me about that.

**Comment by omicreativedev** [comment]
@priyanshu-gupta0503 
* Delete all branches and forks and start over.
* Fork the repo
* Clone your forked version to your local IDE or download the zip file
* Open the folder /pages and make a copy of one of the pages ex. omicreativedev.html
* Rename the copy to something like musicpage.html
* Create a folder in /pages/img as musicpage.jpg
* Put the record picture in the img folder
* Edit musicpage.html and replace the profile-picture with your record picture
* Remove the class profile-photo and and put class="recordcover"
* Put .recordcover in the in page <style> css and define the height, width, etc.
* Replace the info below   With the embed to the soundcloud song
```
   <h1 class="name">@omicreativedev</h1>
  <h2 class="title">Computer Science Student</h2>
 ```
 * Then update the meta data and links 
 DONT WITH PAGE
 For theme
 * Copy the light.css and rename the copy music.css
 * Change the colors to how you like
 DONT WITH PAGE
Update pages_list.txt and themes_list.txt with the respective filenames


Hope this helps!
