### ISSUE TITLE
Create a Haiku Page Template

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#23]
Create an HTML page in the pages folder with a Haiku Poem.
You can use AI to write the Haiku Poem if you like.
Don't forget to add your new page to pages_list.txt
* You can also create a theme (optional) 

Add your name in Contributors.md
Be creative as you like.
Read the Docs First
Give a ⭐
Don't break anything. :)

**Comment by Prince-2204** [comment]
I can do this will you please assign this to me ? I have experience in creating responsive web pages.

**Comment by omicreativedev** [comment]
Yes @Prince-2204 you are assigned.
