### ISSUE TITLE
Create A Happy Birthday Ecard Page

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#24]
The page should say Happy Birthday and work with all themes (at least the background should change)
Yes, you can use additional html or css right inside the page.
You can also make a new theme along with it if you like.
Don't forget to update pages_list.txt
Include a social media image with a picture of a GIFT in the og:image (see thankyou.html and respective folders for example)
You can use canva or AI or design the graphics yourself.

The objective will be that if this page is posted on social media, it will show the og:image from the meta data.
The title can be Happy Birthday and the description should say We have a Surprise For You!
When they click to the link, the page will show a Happy Birthday message :)

Be creative as you like.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by priyanshu-gupta0503** [comment]
hey@omicreativedev  I would like to work on this project pls assign this to me.
The last project which you gave on creating a  song theme was successfuly done had faced an issue in merginging and foeking sorry for that I would be more careful this time.

**Comment by omicreativedev** [comment]
@priyanshu-gupta0503 I left you some help in the other open issue if you would like to try again.

**Comment by priyanshu-gupta0503** [comment]
I would like to try this one for now pls assign me this

**Comment by Aastha7078** [comment]
@omicreativedev assign mam this to me
I want to work on it
