### ISSUE TITLE
Pair Coding Exercise! Make a Theme and Page!

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#25]
Make any page and any theme.
You will be assigned this task with another Assignee.
The first to comment will make the theme, and the second will make the page.
You will both be assigned to the issue.
The PR will be reviewed when you both finish and make a PR.
Be creative as you like.
Read the Docs.
Give a ⭐
Don't break anything. :)
Bonus: I hear that Github awards achievements for pair coding. 
https://7.dev/github-achievements-list/

**Comment by pragyamishra56** [comment]
@omicreativedev I hope you're doing well. I'm Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time hactoberfest contribution to an open-source project, and I'm eager to get started.
I've been looking through the issues. It seems like a great start for me to learn and contribute to this project.
Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed.
Thanks a lot for your time and consideration!

**Comment by omicreativedev** [comment]
This is a paired programming practice. Do you have someone you can add to your forked repository as a contributor collaborator? If not, we may be able to find someone here or maybe I can. I will add help wanted to a tag.

**Comment by pragyamishra56** [comment]
@omicreativedev Mam could you assist me with "Make a Theme and Page" for what kind of it should be
