### ISSUE TITLE
Create A New Profile Page For Yourself

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#34]
Make your own profile page :)
Copy omicreativedev.html
But then make it look different!
Don't forget to update pages_list.txt

Be as creative as you want!
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Priyanshu-su30** [comment]
pls assign me this task.
I want to contribute.

**Comment by omicreativedev** [comment]
@Priyanshu-su30 You are assigned :)
