### ISSUE TITLE
Create a MATRIX Theme & Page

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#38]
Make a Matrix Theme & Page using [The Morpheus Effect](https://rezmason.github.io/matrix/?version=morpheus) <any color!>
Script here: https://github.com/Rezmason/matrix#customization

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.💗

Picture with Neo?
Be as creative as you want with color, animation, styling, etc.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by rajiv57** [comment]
can you please assign this to me?

**Comment by omicreativedev** [comment]
You are assigned @rajiv57

**Comment by rajiv57** [comment]
i have created a pr, hope you like it
