### ISSUE TITLE
Create A Summer Theme

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#4]
Create A Theme for Summer.
Be creative as you like.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by shreyanshig** [comment]
Hi @omicreativedev, please assign this to me

**Comment by omicreativedev** [comment]
@shreyanshig I have assigned another issue to you. When you are finished with that one, if nobody else has asked to do this one, I will happily assign it to you. Or if you would like to switch, let me know. You are welcome to do as many as you like, but hoping they are done one at a time. Since the other issue is more in impressive, I thought you may want a go at that first. Let me know.

**Comment by Hrithik0112** [comment]
Hi @omicreativedev I would love to do this , can you assign this to me ?

**Comment by Hrithik0112** [comment]
@omicreativedev

**Comment by omicreativedev** [comment]
@shreyanshig are you still interested in this?

**Comment by shreyanshig** [comment]
yes

**Comment by tharanithar-r** [comment]
Hello. I am interested in creating the summer theme. Can you assign it to me?
