### ISSUE TITLE
Create a new theme called Protan for Protanopia #wcag #a11y

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#46]
Make an accessible color scheme theme for Protanopia.
This requires some research about what colors to use for this form of visual impairment.

More information can be found here.
- https://www.a11yproject.com/
- http://colorsafe.co/

How To:
- Make a copy of light.css in the /themes folder and rename it to Protan
- Include your name at the top in a comment
- Change the colors and styles
- Make sure the theme looks good with all current pages in the /pages folder and index.html
- Update the themes_list.txt in the root folder
- Update the Contributors.md file in the root folder and add your information

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.??

Be creative.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Rajiiee** [comment]
@omicreativedev pls assign me this! I want to work on this.
