### ISSUE TITLE
Make an accessible color scheme theme called Deut for Deuteranopia. #wcag #a11y

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#48]
Make an accessible color scheme theme for Deuteranopia.
This requires some research about what colors to use for this form of visual impairment.

More information can be found here.
- https://www.a11yproject.com/
- http://colorsafe.co/

How To:
- Make a copy of light.css in the /themes folder and rename it to Deut
- Include your name at the top in a comment
- Change the colors and styles
- Make sure the theme looks good with all current pages in the /pages folder and index.html
- Update the themes_list.txt in the root folder
- Update the Contributors.md file in the root folder and add your information

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.??

Be creative.
Read the Docs.
Give a ?
Don't break anything. :)

**Comment by pragyamishra56** [comment]
@omicreativedev  I hope you're doing well. I'm Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time hactoberfest contribution to an open-source project, and I'm eager to get started.
I've been looking through the issues. It seems like a great start for me to learn and contribute to this project.
Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed.
Thanks a lot for your time and consideration!

**Comment by omicreativedev** [comment]
@pragyamishra56 Yes, you are assigned. Have fun.
Note: You may have to update your branch in a few hours since I'm currently cleaning up the files and refactoring a few things.
