### ISSUE TITLE
Split Script.js into 2 files

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#49]
Currently script.js in the root folder contains the scripts for both the theme switcher and the page switcher used in the index.html

Split the file into the following:

- themeswitch.js
- pagechanger.js

Change index.html to include both scripts.

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.??

Be creative.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Creperi** [comment]
Hi. I did it

**Comment by VETREA** [comment]
Can you assign this issue to me @omicreativedev

**Comment by vishal-sharma-369** [comment]
Solved the issue and created the PR.

**Comment by omicreativedev** [comment]
Thank you @vishal-sharma-369 & @VETREA but I assigned @Creperi as he has done it, but the Issue was left unassigned for some reason. Please feel free to look at other issues. There will no doubt be many more before hacktoberfest is over. Feel free to follow/star to keep updated for more. 

Also, please wait to be officially assigned to **issues** before PR to save yourself work.
The things that can be done without approval are:

- Make a theme (/themes/yourtheme.css) based on light.css; update contributors.md, and update themes_list.txt
and/or
- Make a page (/pages/yourpage.html) based on omicreativedev.html, update contributors.md, and update pages_list.txt

Otherwise, please wait to be assigned issues and bugs 💗

Would love your help with any of the others that are not yet claimed and abandoned :)

**Comment by Creperi** [comment]
For some reason hacktoberfest site always not accepts any contributions.
