### ISSUE TITLE
Move Javascript in /pages html files to External File

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/ThemeSwitcher#50]
Currently each of the files in the /pages folder has Javascript to switch the theme.
Move this code to /pages/themeswitcher_subdir.js
Update thankyou.html and omicreativedev.html with the external script

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.??

Be creative.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Creperi** [comment]
Me.

**Comment by omicreativedev** [comment]
@Creperi You are assigned.

**Comment by omicreativedev** [comment]
@Creperi 
I saw your previous pull. Nice work.
You don't have to update index.html as it's already done.
We need to just do thankyou.html and omicreativedev.html 
Instead of main.js we want to use ./themeswitcher_subdir.js as the filename

**Comment by Creperi** [comment]
Thanks. I was confused.

**Comment by Creperi** [comment]
Anyway i solved the issue
